apiVersion: v2
appVersion: "1.0.0"
description: A Helm chart for Kubernetes
name: swetha-food-ordering-system
version: 1.0.0
type: application
dependencies:
  - name: mysql
    version: "9.0.0"
    repository: "https://charts.bitnami.com/bitnami"